### PR TITLE
Support string and string builder interpolation handler

### PR DESCRIPTION
**Pull request by skarllot**
## The issue or feature being addressed
- Support string interpolation handler for String and StringBuilder

## Details on the issue fix or feature implementation
- Create DefaultInterpolatedStringHandler for supporting high performance string interpolation
- Create AppendInterpolatedStringHandler for supporting high performance string interpolation with StringBuilder
- Create ISpanFormattable to support custom interpolation of an object to a Span
- Create method extensions for StringBuilder to support appending with AppendInterpolatedStringHandler
- Optimize Append method extension for StringBuilder

### CODE REVIEW

**Comment by skarllot** [comment]
Maybe `StringBuilder` extensions are not useful as "method extensions" because the compiler prefer calling string overload instead of with string interpolation.

**Comment by SimonCropp** [comment]
> Maybe StringBuilder extensions are not useful as "method extensions" because the compiler prefer calling string overload instead of with string interpolation.

yeah, i think make it not an extension and add some docs that explains why

**Comment by skarllot** [comment]
> > Maybe StringBuilder extensions are not useful as "method extensions" because the compiler prefer calling string overload instead of with string interpolation.
> 
> yeah, i think make it not an extension and add some docs that explains why

You mean removing `this` and calling as `PolyfillExtensions.Append`?

**Comment by SimonCropp** [comment]
yep

**Comment by skarllot** [comment]
Changes made. Additionally, I've optimized interpolation to use `TryFormat` method extensions.

**Comment by skarllot** [comment]
Rebased to latest commit

**Comment by SimonCropp** [comment]
sorry for the delay. i will deploy this now. should be on nuget in 15

**Pull request merged**
