### PR TITLE
style: fixed Spacing

### PR DESCRIPTION
**Pull request by samtrion**
Caused build errors which I could not fix on my side. See [here](https://github.com/dailydevops/arguments/actions/runs/7978814717/job/21784748563?pr=108)

### CODE REVIEW

**Comment by SimonCropp** [comment]
thanks

**Comment by SimonCropp** [comment]
this is deployed. give nuget 10-15 min to refresh its cache

**Comment by samtrion** [comment]
Thanks, Dependabot has already taken over the update.

**Comment by SimonCropp** [comment]
i just deployed a  2.6.3 that excludes  polyfill files from dotnet format. should make dotnet format run a little quicker. and prevent breakages in the future

**Pull request merged**
