### PR TITLE
Fix some compiler errors that can occur with specific project setups (Memory references)

### PR DESCRIPTION
**Pull request by sbeca**
While testing Polyfill in a few different projects, I hit a few compiler errors which this PR attempts to resolve.

First, in a `netstandard2.0` project that references `System.Threading.Tasks.Extensions` but doesn't reference `System.Memory`, I saw the following errors:

```
/Users/scott/.nuget/packages/polyfill/1.32.0/contentFiles/cs/netstandard2.0/Polyfill/PolyfillExtensions_TextWriter.cs(8,14): error CS0234: The type or namespace name 'Buffers' does not exist in the namespace 'System' (are you missing an assembly reference?)
/Users/scott/.nuget/packages/polyfill/1.32.0/contentFiles/cs/netstandard2.0/Polyfill/PolyfillExtensions_Stream.cs(33,9): error CS0246: The type or namespace name 'Memory<>' could not be found (are you missing a using directive or an assembly reference?)
/Users/scott/.nuget/packages/polyfill/1.32.0/contentFiles/cs/netstandard2.0/Polyfill/PolyfillExtensions_TextReader.cs(34,9): error CS0246: The type or namespace name 'Memory<>' could not be found (are you missing a using directive or an assembly reference?)
/Users/scott/.nuget/packages/polyfill/1.32.0/contentFiles/cs/netstandard2.0/Polyfill/PolyfillExtensions_Stream.cs(56,9): error CS0246: The type or namespace name 'ReadOnlyMemory<>' could not be found (are you missing a using directive or an assembly reference?)
/Users/scott/.nuget/packages/polyfill/1.32.0/contentFiles/cs/netstandard2.0/Polyfill/PolyfillExtensions_TextWriter.cs(29,9): error CS0246: The type or namespace name 'ReadOnlyMemory<>' could not be found (are you missing a using directive or an assembly reference?)
/Users/scott/.nuget/packages/polyfill/1.32.0/contentFiles/cs/netstandard2.0/Polyfill/PolyfillExtensions_TextWriter.cs(55,9): error CS0246: The type or namespace name 'ReadOnlyMemory<>' could not be found (are you missing a using directive or an assembly reference?)
/Users/scott/.nuget/packages/polyfill/1.32.0/contentFiles/cs/netstandard2.0/Polyfill/PolyfillExtensions_TextWriter.cs(76,9): error CS0246: The type or namespace name 'ReadOnlySpan<>' could not be found (are you missing a using directive or an assembly reference?)
/Users/scott/.nuget/packages/polyfill/1.32.0/contentFiles/cs/netstandard2.0/Polyfill/PolyfillExtensions_TextWriter.cs(99,9): error CS0246: The type or namespace name 'ReadOnlySpan<>' could not be found (are you missing a using directive or an assembly reference?)
```

This was fixed in this PR by adding the `MEMORYREFERENCED` define in a few extra places.

~~Then, in another project that defined its own `Debug` class, I saw the following errors:~~

```
/Users/scott/.nuget/packages/polyfill/1.32.0/contentFiles/cs/netstandard2.0/Polyfill/Nullability/NullabilityInfoContext.cs(507,13): error CS0104: 'Debug' is an ambiguous reference between 'MBT.Utilities.Debug' and 'System.Diagnostics.Debug'
/Users/scott/.nuget/packages/polyfill/1.32.0/contentFiles/cs/netstandard2.0/Polyfill/Nullability/NullabilityInfoContext.cs(541,13): error CS0104: 'Debug' is an ambiguous reference between 'MBT.Utilities.Debug' and 'System.Diagnostics.Debug'
```

~~This was solved by adding some explicit `using Debug = System.Diagnostics.Debug;` lines in Polyfill.~~

EDIT: Second issue/fix extracted into separate PR #122.

### CODE REVIEW

**Comment by SimonCropp** [comment]
can you add a new project that replicates this scenario. so the changes can be verified

**Comment by sbeca** [comment]
Yep, I can look into doing that

**Comment by sbeca** [comment]
@SimonCropp: I have added a new project (`ConsumeTasksWithNoMemory.csproj`) and a new class (`Debug.cs`) that replicates these 2 issues. They both fail to compile when included in `main` but compile fine with the changes in this PR.

**Comment by sbeca** [comment]
Sorry about the delay, I have now split the Debug change out into PR #122

**Comment by SimonCropp** [comment]
thanks. will deploy now. pending nuget updating its cache

**Pull request merged**
