### PR TITLE
revert array range support

### PR DESCRIPTION
**Pull request by SimonCropp**
@gao-artur i had tor ever this since when consumed it causes a build error

```
Error CS1685 : The predefined type 'RuntimeHelpers' is defined in multiple assemblies in the global alias
```

basically if internalvisibleto or PolyPublic is used. it causes a type conflict

### CODE REVIEW

**Comment by gao-artur** [comment]
Ok, thanks for update

**Comment by SimonCropp** [comment]
it also broke some legit uses of RuntimeHelpers like GetHashCode https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimehelpers.gethashcode?view=net-8.0

**Comment by gao-artur** [comment]
Interesting. The PdfSharp lib [overrides](https://github.com/empira/PDFsharp/blob/master/src/foundation/src/shared/src/PdfSharp.System/System/CompilerServices.cs#L291) `GetSubArray` without `InitializeArray` method for `net4.7.2` and `netstandard2.0` and doesn't have any compiling errors. They also have the `CS1685` warning, but they just decided to [suppress](https://github.com/empira/PDFsharp/blob/master/src/foundation/src/MigraDoc/tests/MigraDoc.DocumentObjectModel.Tests/MigraDoc.DocumentObjectModel.Tests.csproj#L5-L8) it. I assume they didn't encounter any problem with `GatHashCode` too.

**Comment by gao-artur** [comment]
Ok, when I add `ReadOnlySpan<Char> bar = ['d'];` somewhere in their code, it starts to fail with the same compile error. I tried other options, but it was the only statement that caused the compiler to fail. All these work with no issues:
```c#
Span<Char> bar = ['d'];
ReadOnlySpan<Char> bar = new char['d'];
ReadOnlySpan<Char> bar = "d".AsSpan();
```

**Comment by SimonCropp** [comment]
i did consider adding a suppression to the msbuild file that ships with polyfill. but unfortunately we can suppress it for "just that that type". we we would be hiding potentially legitimate warnings for other types

**Pull request merged**
